main: eu.hiddenite.perms.bukkit.PermsBukkitPlugin
name: HiddenitePerms
version: 1.0.0
api-version: 1.16
author: Hiddenite
permissions:
  hiddenite.perms.bypass:
    description: "Bypasses the blocked commands."
    default: op
